### PR TITLE
Added classic_light plugin for devices without rollback feature.

### PR DESCRIPTION
**Pull request by pszulczewski**
Adding light version of classic plugin for devices without rollback feature available.

### CODE REVIEW

**Comment by coxoperationsengineer** [comment]
This is an important feature for me as well, @hellt any idea when you guys might could merge this? 7705, 7210's, etc back on 9.0R9.

**Comment by hellt** [comment]
Sorry, I got dragged back with some other stuff.
I need to have a look at it next week.


To speed this up, can you give it a spin and test it with your 7210/etc
running that old sw releases?

**Comment by coxoperationsengineer** [comment]
@hellt yep, not a problem, sorry for the delay, I am just getting back to the office today due to direct hit from Hurricane Sally and recovery efforts, so will carve some time out to run this through.  We have 20K+ in most every flavor of 72xx deployed and are at 9.0R9-1 which is where I noticed the playbook was failing which led me to finding this issue posted, so I can grab some output from those.

**Comment by pszulczewski** [comment]
@coxoperationsengineer 

If you would like to test the classic_light plugin you just have to download it from https://github.com/pszulczewski/ansible-networking-collections/tree/classic_light
and just put plugins directory to your ansible collection location under nokia/sros/ to replace plugins dir.

**Comment by hellt** [comment]
Hi @coxoperationsengineer 
before merging this we'd like to know if the changes worked for you. Did you have time to give it a spin?

**Comment by coxoperationsengineer** [comment]
> Hi @coxoperationsengineer
> before merging this we'd like to know if the changes worked for you. Did you have time to give it a spin?

Hey @hellt and @pszulczewski I did get to test this in a very limited scope, a 7210 MXP on 9.0R9-1 with a simple config change using the sros_classic_cli_config_demo.yml playbook, and it was successful.  No errors, the box took the change, I see it did an admin save, so all the things I would expect top level, look good.   I need to test it out on a few more devices, with some more complicated changes, but I literally could not perform any of this before dropping the plugin's in the folder.  

@pszulczewski Do you know of anything specifically that you feel might slip it up? I can try to target some complicated changes or scenarios if you are aware of any.

**Comment by pszulczewski** [comment]
I don't see anything specific that you should give extra attention.
Honestly classic_light plugin is the same code as classic plugin but just without using rollback feature.
I use classic plugin in live production environment without any issues.
Classic light I tested on vSIMs only and didn't face any problems.

**Comment by wisotzky** [comment]
@pszulczewski, I would agree to what you are saying.

I might give it a deeper look if this could get further improved. At least to me it feels, that we could support proper "-diff" mode, to understand what changes are contained. However, in this case would not be able to leverage the nodal compare - so we would need to download the entire config before and after the change (what happens to my knowledge anyways) and run a "diff" in the python script.

**Comment by wisotzky** [comment]
All, I've done some more testing and feel comfortable enough to have the change merged. I've renamed from 'nokia.sros.classic_light' to just 'nokia.sros.light' - as it feels more simplistic.

**Comment by wisotzky** [comment]
@hellt, @pszulczewski,
In my view, we should remove the support for 'onbox diff' as this gives the wrong impression that we are able to properly support the change detection and --diff mode. Removing it is the much cleaner approach, while we could propose to change the 'cli_config' module.

Background:
In the case of the NETCONF configuration module, we basically take a config snapshot before and after the configuration change was executed. Those snapshots would be compared within Ansible which allows both, change indication and --diff mode. As 'cli_config' takes a config snapshot at the beginning anyways, the extra work to take another snapshot sounds reasonable to me. In fact, this would only be issued for plugins neither support 'onbox diff' nor 'generate diff'.

**Comment by coxoperationsengineer** [comment]
@hellt @pszulczewski @wisotzky Thank you for the merge! One thing I am trying out this morning, I don't see any documentation that explicitly states you are going to perform the admin save after the cli_config task, maybe I missed it if so.  I mention that because I see that trips up the "asterisk" method and displays "ok" if I send admin save with the config snippet, which out of habit most people might do.  Just tossing out some ideas, could perhaps display something to the user like a warning message or something of the like if you catch "admin save" in the config or a changed_when condition.

Another common task for us is validating the corresponding "show" command of whatever we sent, so I was thinking at some point it might be nice to have a validation variable where the user can provide a command and expectant result so that we make it semi transactional, one config task, one validation task, next config task, next validation task.  We really struggle creating safe complex plays that we can peel back without batching it out.  If anything just the order of operations of backing out a change can be cumbersome without NETCONF, think LSP, SDP, Service, or port/router interface/protocols, and then realizing the interface name is wrong and reversing them out, but is the reality we live in, curious to see what thoughts and approaches you guys might take. 

Off Topic, what vSim's are you guys using for Nokia, I recall only the 7750 image was available last time I inquired with our rep.

**Comment by wisotzky** [comment]
@hellt,
I've tried the change on `cli_config` on my Ansible 2.9 bench and it is absolutely possible. I've added an issue against the new netcommon collection to have this change added:
https://github.com/ansible-collections/ansible.netcommon/issues/156

Let's see, if @trishnaguha is adding the code. If not, I can apply the change and make it a PR. But in the past it took typically 6-12 months until my PRs got merged into Ansible, so I am avoiding extra work now and let Ansible team fix it.

Keep in mind, that from Ansible 2.10 onwards collections are the default delivery mechanism even for most of the content that was part of Ansible 2.9 before:
https://github.com/ansible-collections/ansible.netcommon

**Comment by wisotzky** [comment]
> One thing I am trying out this morning, I don't see any documentation that explicitly states you are going to perform the admin save after the cli_config task, maybe I missed it if so.

We don't add the `admin save` so this would need to be done by the playbook author. You should not use the `cli_config` module for this but the `cli_command` - else you impact the star indicator that config was changed.

> Another common task for us is validating the corresponding "show" command of whatever we sent, so I was thinking at some point it might be nice to have a validation variable where the user can provide a command and expectant result so that we make it semi transactional, one config task, one validation task, next config task, next validation task.

You can run `show` commands using `cli_command`. For audits/checks one might use assertions in Ansible. You may have a look into the test automation that is done by Ansible, as this is a very reliable resource on how this could be done. However, parsing of CLI show commands might not be trivial. Maybe you can poke around existing CLI output parsers like textFSM for this.

> Off Topic, what vSim's are you guys using for Nokia, I recall only the 7750 image was available last time I inquired with our rep.

I am using exclusively 7x50 VSIM in my bench.

**Comment by coxoperationsengineer** [comment]
@wisotzky Ah interesting, I must have inadvertently saved at some point during my previous testing, but running again and logging into the box I see the asterisk is still there waiting for me to send admin save.  My apologies!

Yeah we are typically using Python and TextFSM today or pySNMP to SET the changes since its extremely fast compared to SSH work, but the move to Ansible is to get more reach and grow the culture of automation around the company.  Right now, its a handful of engineers who can both do the work and code, and several hundred more that just do the work, and were hoping Ansible lowers the barrier to entry and gets more people involved, so we all appreciate the work you guys are doing here.  I am admittedly new to Ansible, but not Python, so I am having to reverse into it :) appreciate the recommendations.

I got excited that there might be more VSIM's!  We have 700+ 7x50 devices deployed, but our main transactional work is on the access side with the 7210 SAS line.

**Comment by hellt** [comment]
@coxoperationsengineer if speed is one of the prime objectives, I would rather look at scrapli and/or nornir, but not pySNMP ;)

**Comment by pszulczewski** [comment]
@coxoperationsengineer  Sven pointed you to the right direction to use Ansible assertions with textFSM to transform cli command output into structured data and use assert module on top of that to verify your changes.

Here is an example how you can verify an ospf neighbor, it can be prepended with cli_config task to configure a new peer between two network elements.
```
---
- name: GET SHOW COMMAND
  cli_command:
    command: show router ospf neighbor
  register: cli_output

- name: PARSE SHOW OUTPUT WITH TEXTFSM
  set_fact:
    textFSM_facts: "{{ cli_output.stdout | parse_cli_textfsm(nokia_sros_show_router_ospf_neighbor.template) }}"

- name: TEST OSPF NEIGHBOR
  assert:
    that:
      - textFSM_facts | list | count > 0
      - textFSM_facts | selectattr('RtrId', 'eq', ospf_peer_ip) | selectattr('State','ne','Full') | list | count == 1
    fail_msg: "OSPF TEST FAILED."
    success_msg: "OSPF TEST PASSED"
  vars:
    ospf_peer_ip: 10.0.0.5
```
Attributes `RtrId& `State are from textFSM template.

Here is the template:
```
Value Key,Required Interface (.*?)
Value AreaId (\S+)
Value RtrId (\d+\.\d+\.\d+\.\d+)
Value State (\S+)
Value Pri (\d+)

Start
  ^(\s+)?${Interface}\s\s+${RtrId}\s+${State}\s+${Pri}
  ^\s+${AreaId} -> Record
```
TextFSM template returns list of dicts, `selectattr() is a Jinja filter and what looks for an element of the output list with Router ID equal to `ospf_peer_ip variable and state Full.

**Comment by coxoperationsengineer** [comment]
> @coxoperationsengineer if speed is one of the prime objectives, I would rather look at scrapli and/or nornir, but not pySNMP ;)

@hellt I need to give scrapli a try, I just starred the repo, thanks for suggestion!  

Nornir is good as well with threading built in, but I wrote an Asyncio based script with pySNMP, that for simple things like non-service affecting, on/off, type attributes, for example we wanted to suppress a bunch of event controls recently and add a new global Syslog ID for TS Platinum, and I was able to send 1.6 million OID's worth of changes, to 11K hosts in 149 minutes on a single CPU most recently, and rather than scraping the CLI to make sure its right with SSH, I can query the value is the same I set it to afterwards with a GET, so its speed was alluring..on the surface at least.  That said, the dark side of that was Asyncio, and pySNMP are frustrating to develop with, no one on my team understands how it works but me, and I likely would not go down that route again for our next change at scale, so you all's suggestions are much appreciated.

@pszulczewski you are the man, appreciate you giving me a working example, I have alot of textFSM templates already created, so now I know how to make use of them in Ansible as we go down this path with some of the new guys.

**Pull request merged**
